# Generated by Django 4.2.28 on 2026-02-20 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('passed', 'Passed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('selected_country', models.CharField(blank=True, max_length=100)),
                ('selected_suggestion', models.CharField(blank=True, max_length=255)),
                ('checkin_date', models.CharField(blank=True, max_length=50)),
                ('checkout_date', models.CharField(blank=True, max_length=50)),
                ('selected_month', models.CharField(blank=True, max_length=50)),
                ('guest_count', models.IntegerField(blank=True, null=True)),
                ('is_mobile', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('step_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('screenshot_path', models.CharField(blank=True, max_length=500)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('test_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='automation.testrun')),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='SelectedDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_name', models.CharField(max_length=50)),
                ('checkin_date', models.CharField(max_length=50)),
                ('checkout_date', models.CharField(max_length=50)),
                ('next_month_clicks', models.IntegerField(default=0)),
                ('test_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='selected_dates', to='automation.testrun')),
            ],
        ),
        migrations.CreateModel(
            name='SearchListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('price', models.CharField(blank=True, max_length=100)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('listing_url', models.URLField(blank=True, max_length=1000)),
                ('position', models.IntegerField()),
                ('is_selected', models.BooleanField(default=False)),
                ('test_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='automation.testrun')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='NetworkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('resource_type', models.CharField(blank=True, max_length=50)),
                ('step_name', models.CharField(blank=True, max_length=255)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('test_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_logs', to='automation.testrun')),
            ],
            options={
                'ordering': ['logged_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('subtitle', models.TextField(blank=True)),
                ('image_urls', models.JSONField(default=list)),
                ('page_url', models.URLField(blank=True, max_length=1000)),
                ('test_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='listing_detail', to='automation.testrun')),
            ],
        ),
        migrations.CreateModel(
            name='GuestSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adults', models.IntegerField(default=0)),
                ('children', models.IntegerField(default=0)),
                ('infants', models.IntegerField(default=0)),
                ('pets', models.IntegerField(default=0)),
                ('total_guests', models.IntegerField(default=0)),
                ('test_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guest_selection', to='automation.testrun')),
            ],
        ),
        migrations.CreateModel(
            name='ConsoleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('log', 'Log'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('debug', 'Debug')], default='log', max_length=20)),
                ('message', models.TextField()),
                ('step_name', models.CharField(blank=True, max_length=255)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('test_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='console_logs', to='automation.testrun')),
            ],
            options={
                'ordering': ['logged_at'],
            },
        ),
        migrations.CreateModel(
            name='AutoSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('has_map_icon', models.BooleanField(default=False)),
                ('position', models.IntegerField()),
                ('is_selected', models.BooleanField(default=False)),
                ('test_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='automation.testrun')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
